In [ ]:
e=np.ones((8,4))
print(e)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
import numpy as np

In [ ]:
a=np.random.rand(1)
print(a)

[0.33774541]


In [ ]:
b=np.random.rand(8,4)
print(b)

[[0.61022913 0.31915817 0.92696076 0.35241207]
 [0.08763641 0.80778529 0.76516328 0.5759775 ]
 [0.93828765 0.66463484 0.26581922 0.06358916]
 [0.54600886 0.98415915 0.40017377 0.41763623]
 [0.67182015 0.32459871 0.11574322 0.27530793]
 [0.68145765 0.95886254 0.07845877 0.78362999]
 [0.09557125 0.66527418 0.46317755 0.12904877]
 [0.22195369 0.6253433  0.29057924 0.3338961 ]]


In [ ]:
b=10*np.random.rand(8,4)
print(b)

[[7.35006443 0.14916663 1.76737955 4.63051758]
 [3.42050147 7.9001144  5.35016643 4.76773327]
 [6.35398539 8.18919243 4.72284485 3.80670806]
 [1.50007446 9.96775186 5.2708218  5.03050082]
 [2.13436321 9.49585042 3.67651551 6.37604585]
 [6.43947709 9.87441721 6.06829171 8.10245741]
 [6.04258812 9.791279   7.27923555 0.02327203]
 [0.12142499 1.90201817 2.40199736 8.81118608]]


In [ ]:
b=np.floor(10*np.random.rand(8,4))
print(b)

[[9. 9. 2. 5.]
 [5. 2. 8. 5.]
 [2. 5. 0. 1.]
 [2. 2. 9. 1.]
 [1. 3. 3. 4.]
 [3. 6. 0. 4.]
 [7. 5. 5. 0.]
 [7. 6. 3. 3.]]


In [ ]:
a=np.arange(1,33).reshape(8,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [ ]:
np.vsplit(a,4)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24]]),
 array([[25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [ ]:
np.vsplit(a,3)

ValueError: array split does not result in an equal division

In [ ]:
np.vsplit(a,(1,3,6))

[array([[1, 2, 3, 4]]),
 array([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]),
 array([[25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [ ]:
a=np.arange(1,33).reshape(4,8)
print(a)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]


In [ ]:
np.hsplit(a,4)

[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26]]),
 array([[ 3,  4],
        [11, 12],
        [19, 20],
        [27, 28]]),
 array([[ 5,  6],
        [13, 14],
        [21, 22],
        [29, 30]]),
 array([[ 7,  8],
        [15, 16],
        [23, 24],
        [31, 32]])]

In [ ]:
np.hsplit(a,(2,7 ))

[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26]]),
 array([[ 3,  4,  5,  6,  7],
        [11, 12, 13, 14, 15],
        [19, 20, 21, 22, 23],
        [27, 28, 29, 30, 31]]),
 array([[ 8],
        [16],
        [24],
        [32]])]

tignometry

In [ ]:
 np.pi

3.141592653589793

In [ ]:
v=[np.pi/4,np.pi/3,np.pi/2,np.pi]
print(v)

[0.7853981633974483, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]


In [ ]:
b=np.rad2deg(v)
print(b)

[ 45.  60.  90. 180.]


In [ ]:
np.deg2rad(b)

array([0.78539816, 1.04719755, 1.57079633, 3.14159265])

In [ ]:
np.sin(1)

0.8414709848078965

In [ ]:
np.cos(1)


0.5403023058681398

In [ ]:

np.tan(1)

1.5574077246549023

In [ ]:
st=np.array([23,45,67,89,21,34])

In [ ]:
np.mean(st)

46.5

In [ ]:
np.median(st)

39.5

In [ ]:
np.var(st)

597.9166666666666

In [ ]:
np.std(st)

24.452334585202017

In [ ]:
c=np.arange(1,5).reshape(2,2)
print(c)

[[1 2]
 [3 4]]


In [ ]:
np.linalg.inv(c)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
d=np.arange(1,25).reshape(6,4)
print(d)
print(np.argmax(d))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
23


In [ ]:
w=np.floor(10*np.random.rand(24)).reshape(6,4)
print(w)

[[2. 9. 4. 0.]
 [4. 6. 3. 2.]
 [4. 4. 2. 3.]
 [9. 5. 7. 0.]
 [4. 2. 2. 5.]
 [1. 6. 5. 7.]]


In [ ]:
print(np.argmax(w))

1


In [ ]:
c=10*np.random.rand(24).reshape(6,4)
print(c)

[[0.88154571 8.80232909 6.57320774 0.01897956]
 [9.72056378 0.95403888 1.96717758 0.08287385]
 [1.61591109 6.85799413 7.25203413 6.54706867]
 [1.686175   6.7048966  2.97008887 5.00272399]
 [9.67672259 3.40326774 4.51619177 6.10234591]
 [1.54907179 3.37033898 1.81703891 1.43383006]]


In [ ]:
print(np.argmax(c))

4


In [ ]:
print(np.argmax(c,axis=1))

[1 0 2 1 0 1]


In [ ]:
print(np.argmax(c,axis=0))

[1 0 2 2]


In [ ]:
print(np.argmin(c,axis=0))

[0 1 5 0]


In [ ]:
print(np.argmin(c,axis=1))

[3 3 0 0 1 3]


searching the indeces based on conditions

In [ ]:
s=np.array([34,56,7,17,88,91])
print(np.where(s%2==0))


(array([0, 1, 4]),)


In [ ]:
s=np.array([24,16,7,17,54,60])
print(np.where(s%6==0))


(array([0, 4, 5]),)


In [ ]:
a=np.array([34,56,7,17,88,91])
x=np.searchsorted(a,17)
print(x)


0


In [ ]:
f=np.array([2,3,4,5,6,7,8,9])
g=np.searchsorted(f,7)
print(g)


5


In [ ]:
arr=np.array(['banana','cherry','apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [ ]:
print(np.sort(a))

[ 7 17 34 56 88 91]


In [ ]:
err=np.array([[3,2,4],[5,0,1]])
print(np.sort(err))

[[2 3 4]
 [0 1 5]]


In [ ]:
bo=np.array([True,False,True])
print(np.sort(bo))

[False  True  True]


In [ ]:
trr=np.array([40,42,50,44,67,78])
filrt=np.where(trr%2==0)
print(filrt)

(array([0, 1, 2, 3, 5]),)


In [ ]:
trr[filrt]

array([40, 42, 50, 44, 78])

In [ ]:
names=np.array(["veen","lah","tej","kus","kav","var","sadh"])
initials=np.array(["j","y","e","b","t","v","m"])
for i,j in zip(initials,names):
  print(i,".",j)

j . veen
y . lah
e . tej
b . kus
t . kav
v . var
m . sadh


In [ ]:
a1=np.array([10,20,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
n1=np.multiply(a1,a2)
print(n1)

[ 200  420  660  920 1200 1500]


In [ ]:
a1=np.array([10,20,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
n2=np.divide(a1,a2)
print(n2)


[0.5        0.95238095 1.36363636 1.73913043 2.08333333 2.4       ]


In [ ]:
a1=np.array([10,20,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
n3=np.mod(a1,a2)
print(n3)

[10 20  8 17  2 10]


In [ ]:
a1=np.array([10,20,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
n4=np.divmod(a1,a2)
print(n4)

(array([0, 0, 1, 1, 2, 2]), array([10, 20,  8, 17,  2, 10]))


logerthims

In [ ]:
a1=np.arange(1,10)
print(a1)
print(np.log10(a1))

[1 2 3 4 5 6 7 8 9]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


In [ ]:
q=1.2
print(np.log(q))

0.1823215567939546


In [ ]:
q=1.2
print(np.log2(q))

0.2630344058337938


In [ ]:
q=1.2
print(np.log10(q))

0.07918124604762482


In [ ]:
print(np.log(a2))

[2.99573227 3.04452244 3.09104245 3.13549422 3.17805383 3.21887582]


In [ ]:
print(np.log2(a2))

[4.32192809 4.39231742 4.45943162 4.52356196 4.5849625  4.64385619]


In [ ]:
print(np.log10(a2))

[1.30103    1.32221929 1.34242268 1.36172784 1.38021124 1.39794001]


In [ ]:
y=np.array([5,6,7,10])
x=np.cumsum(y)
print(x)

[ 5 11 18 28]


In [ ]:
y=np.array([5,6,7,10])
x=np.cumprod(y)
print(x)

[   5   30  210 2100]


In [ ]:
y=np.array([15,25,15,10])
x=np.diff(y)
print(x)

[ 10 -10  -5]


In [ ]:
num1=455
num2=665
v=np.lcm(num1,num2)
print(v)

8645


In [ ]:
num1=455
num2=665
v=np.gcd(num1,num2)
print(v)

35


In [ ]:
a=np.array([12,15,60])
g=np.gcd.reduce(a)
print(g)

3


In [ ]:
a=np.array([12,15,60])
g=np.lcm.reduce(a)
print(g)

60
